numpy indexing and slicing of vector

In [1]:
import numpy as np

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[0]

np.int64(11)

In [5]:
arr[5]

np.int64(16)

In [6]:
arr[9]

np.int64(20)

array slice h bro 

In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:5]

array([11, 12, 13, 14, 15])

In [9]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [11]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[1:5]

array([12, 13, 14, 15])

In [13]:
arr[2:5]

array([13, 14, 15])

In [14]:
arr[-1:-1]

array([], dtype=int64)

In [15]:
arr[-1::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [16]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
arr[1:6:2]

array([12, 14, 16])

In [18]:
arr[4:]

array([15, 16, 17, 18, 19, 20])

In [20]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [21]:
arr_slice

array([14, 16, 18, 20])

numpy indexing and slicing of matrix

In [22]:
arr=np.arange(1,31,).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
arr[0]

array([1, 2, 3, 4, 5])

In [24]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[2]

array([11, 12, 13, 14, 15])

In [29]:
arr[0,0]

np.int64(1)

bhai column find krna ho tooo

In [ ]:
arr[1,0]  

np.int64(6)

In [31]:
arr[0,4]

np.int64(5)

In [32]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [33]:
arr[:,1]

array([ 2,  7, 12, 17, 22, 27])

In [34]:
arr[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

mujhe isme access krna h 2,3,
                         7,8 ye portion 

In [37]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [38]:
slice

array([[2, 3],
       [7, 8]])

In [39]:
arr[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [42]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

boolean indexing

In [43]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

hme array me even element rakhna h 

In [44]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [47]:
arr=arr[bool_index]

In [46]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
arr

array([12, 14, 16, 18, 20])