array opeartion
arithmetic operation

In [45]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [4]:
arr1 = a1+a2
arr1

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a2-a1

array([5, 5, 5, 5, 5])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
#  floor division
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

broadcasting

In [10]:
l=[10,20,30,40]
arr=np.array(l)

In [11]:
arr+10

array([20, 30, 40, 50])

in 2 d array 

In [13]:
arr= np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr *11

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 110],
       [121, 132, 143, 154, 165],
       [176, 187, 198, 209, 220],
       [231, 242, 253, 264, 275]])

deep and shallow copy

In [16]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [19]:
slice

array([1, 2, 3, 4, 5])

In [21]:
slice=slice +10

In [22]:
slice

array([11, 12, 13, 14, 15])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6] * 10

array([50, 60])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

ye deep copy h bhai 

In [26]:
b=a

In [27]:
b[0]=101

In [28]:
b

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [29]:
a

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

agar tum copy krna chahte ho lekin 1st array change na ho too uske liye

In [31]:
a=np.array([10,20,30,40,50])


In [33]:
b=a
b[0]=11
b

array([11, 20, 30, 40, 50])

In [34]:
a

array([11, 20, 30, 40, 50])

In [35]:
b=a.copy()
b[0]=1
b

array([ 1, 20, 30, 40, 50])

In [36]:
a

array([11, 20, 30, 40, 50])


matrix opeartion

In [37]:
A =np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
B

array([[5, 6],
       [7, 8]])

In [40]:
# multiplication operation
# matrix multiplication 

A @ B

array([[19, 22],
       [43, 50]])

In [41]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [42]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [43]:
B.T

array([[5, 7],
       [6, 8]])

advance array manipulation 
stacking array - two matrix ko stack nhi kr sakte 
two vector ko kr sakte h
stack are of three type horizontal,vertical,simple
stack mean jorna 

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [46]:
B

array([[5, 6],
       [7, 8]])

In [47]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [49]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

spilting array
split are of two types horizontal and vertical

In [53]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [59]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [66]:
a= np.vsplit(c,4)

In [69]:
for i in a :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
