Valid Sudoku

In [1]:
import numpy as np

In [31]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [32]:
s.sum()

np.int64(405)

In [33]:
b=np.sum(s,axis=1)

b[b==45]


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [34]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [35]:
for i in b :
    print(i)

45
45
45
45
45
45
45
45
45


In [43]:
for i in b :
    if(i!=45):
        print("not valid")
        break
    else:
        print("valid for row ")

valid for row 
valid for row 
valid for row 
valid for row 
valid for row 
valid for row 
valid for row 
valid for row 
valid for row 


In [40]:
c=np.sum(s,axis=0)
c

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [41]:
c==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
for i in c :
    if(i!=45):
        print("invalid sudoco")
        break
    else:
        print("valid sudoco for column")
        
        
    

valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column
valid sudoco for column


In [45]:
s[:]

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [47]:
d= s[0:3,0:3]
d

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [48]:
d

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [49]:
np.sum(d,axis=1)

array([12, 15, 18])

In [50]:
np.sum(d)

np.int64(45)

In [51]:
np.sum(d,axis=0)

array([12, 19, 14])

In [52]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [53]:
s[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [54]:
s[:]

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [55]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


General Questions


In [56]:
for i in range(0,9,3):
    for j in range(0,9,3):
       n=s[i:i+3,j:j+3]
       print(n.sum())

45
45
45
45
45
45
45
45
45


2nd question 

In [87]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#Get the shape of the matrix.

In [58]:
data.shape

(5, 3)

find the average age of student

In [61]:
np.mean(data[:,0])

np.float64(18.4)

#Extract Math marks of all students.

In [62]:
data[:,1]

array([85, 92, 76, 65, 90])

#Find the highest Science mark.

In [64]:
m=data[:,2]
m.max()

np.int64(95)

#Get details of the student who scored more than 90 in Math.

In [66]:
data[data[:,1]>90]

array([[19, 92, 88]])

#Increase Math marks of all students by 5.

In [68]:
data=data[:,1]+5
data

array([90, 97, 81, 70, 95])

#Find how many students are younger than 19.

In [73]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [77]:
len(data[data[:,0] < 19])


3

#Calculate the average marks in each subject (column-wise mean).

In [79]:
np.mean(data[:,1])

np.float64(81.6)

In [81]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])


#Get data of students who scored at least 80 in both subjects.

In [83]:
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

#Replace all Science marks < 75 with 0.

In [88]:
data[:,2][data[:,2]<75]=0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])