In [3]:
import numpy as np 

In [7]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [11]:
x=[1,2,3,4,5,'hello']

In [12]:
np.array(x)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [15]:
y=[1,2,3.5]

In [16]:
np.array(y)

array([1. , 2. , 3.5])

In [18]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
a=[2.5,3.4,5.6,1]

In [4]:
np.array(a)


array([2.5, 3.4, 5.6, 1. ])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

ye one dimensional h 

In [7]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

ye two dimensional h 

In [8]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [10]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

linesspace - linear space

In [15]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

random generation function

In [18]:
np.random.rand(3)

array([0.25696726, 0.59665172, 0.1944292 ])

In [20]:
np.random.randn(10)

array([ 1.45426256, -0.0478247 ,  1.00661935, -0.17958218, -0.27115506,
        0.68218582,  1.71255678,  0.14646372,  0.89800615,  0.51453665])

In [25]:
np.random.randint(6)

3

In [26]:
np.random.randint(10,20)

12

In [27]:
np.random.randint(10,20,10)

array([15, 10, 11, 11, 15, 12, 14, 13, 12, 14], dtype=int32)

array attributes

In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print("ndim",arr.ndim)

ndim 2


In [31]:
print("shape",arr.shape)

shape (3, 3)


In [32]:
print("size",arr.size)

size 9


In [33]:
print("dtype",arr.dtype)

dtype int64


In [34]:
print("itemsize",arr.itemsize)

itemsize 8


In [35]:
print("nbytes",arr.nbytes)

nbytes 72


In [36]:
print("transpose",arr.T)

transpose [[1 4 7]
 [2 5 8]
 [3 6 9]]


array methods 

In [37]:
arr=np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr=np.array([10,20,30,40,50])
arr.resize(2,2)
arr

array([[10, 20],
       [30, 40]])

In [44]:
arr=np.array([[11,22,33],[44,55,66]])
arr

array([[11, 22, 33],
       [44, 55, 66]])

In [46]:
arr.flatten()

array([11, 22, 33, 44, 55, 66])

In [47]:
arr=np.array([[11,22,33],[44,55,66]])
arr

array([[11, 22, 33],
       [44, 55, 66]])

In [48]:
arr.ravel()

array([11, 22, 33, 44, 55, 66])

In [49]:
arr.astype(float)

array([[11., 22., 33.],
       [44., 55., 66.]])

In [51]:
arr.astype(int)

array([[11, 22, 33],
       [44, 55, 66]])

In [52]:
arr.tolist()

[[11, 22, 33], [44, 55, 66]]

In [53]:
arr=np.array([2.4,3,5,6,7,8,9])
arr

array([2.4, 3. , 5. , 6. , 7. , 8. , 9. ])

In [54]:
arr.astype(int)

array([2, 3, 5, 6, 7, 8, 9])

In [55]:
arr_copy=arr.copy()
arr_copy

array([2.4, 3. , 5. , 6. , 7. , 8. , 9. ])

In [56]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a.sum()

np.int64(45)

In [58]:
a.mean()

np.float64(5.0)

In [59]:
a.max()

np.int64(9)

In [60]:
a.min()

np.int64(1)

In [61]:
a.argmax()

np.int64(8)

In [62]:
a.argmin()

np.int64(0)

In [63]:
a.std()

np.float64(2.581988897471611)

In [64]:
a.var()

np.float64(6.666666666666667)

In [65]:
arr=np.array([3,1,2,0])
arr

array([3, 1, 2, 0])

In [66]:
np.sort(arr)

array([0, 1, 2, 3])

In [67]:
arr.argsort()

array([3, 1, 2, 0])

In [68]:
np.argwhere(arr)

array([[0],
       [1],
       [2]])

In [70]:
arr=np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [73]:
arr.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [74]:
arr.swapaxes(0,1)

array([[1, 3, 5],
       [2, 4, 6]])

In [75]:
arr.swapaxes(1,0)

array([[1, 3, 5],
       [2, 4, 6]])

In [76]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [77]:
arr.clip(3,5)

array([3, 3, 3, 4, 5])

In [78]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [79]:
arr.clip(50,100)

array([ 50,  50,  50,  50,  50,  60,  70,  80,  90, 100])

In [80]:
arr=np.array([1,2,4,3,0])
arr

array([1, 2, 4, 3, 0])

In [81]:
arr.all()

np.False_

In [82]:
arr.any()

np.True_

In [83]:
arr.nonzero()

(array([0, 1, 2, 3]),)

In [84]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.sum(arr,axis=(0))

array([12, 15, 18])

In [90]:
np.sum(arr,1)

array([ 6, 15, 24])

In [91]:
arr.mean()

np.float64(5.0)

In [99]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr=arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
arr=arr.reshape(3,4)

In [106]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])